### ISSUE TITLE
[question] replace inception with resnet18

### ISSUE THREAD

**Issue by jS5t3r** [WindVChen/DiffAttack#13]
Can I just replace the inception with a pre-trained resnet18?

Would it run on the [demo data](https://github.com/WindVChen/DiffAttack/tree/main/demo) seamlessly?

**Comment by WindVChen** [comment]
Hi @jS5t3r ,

Yes, you can seamlessly replace the Inception model with a pre-trained ResNet18. An easier way to achieve this is by adding your desired model to the [model_selection](https://github.com/WindVChen/DiffAttack/blob/8bb05a889204c960d731a58cd42379c2a8d46a82/other_attacks.py#L21C26-L21C26) function and the [models_transfer_name](https://github.com/WindVChen/DiffAttack/blob/8bb05a889204c960d731a58cd42379c2a8d46a82/other_attacks.py#L93C13-L93C13) list. Simply expand the script in [other_attacks.py](https://github.com/WindVChen/DiffAttack/blob/main/other_attacks.py) as follows:

```python
def model_selection(name):
    ...
    elif name == "resnet_18":
        model = models.resnet18(pretrained=True)
    ...

def model_transfer(...):
    ...
        models_transfer_name = ["resnet_18", ...]
    ...
```

**Comment by jS5t3r** [comment]
Thanks for the fast response :)
