### ISSUE TITLE
Can you provide the ‘STCAR_Res_94.35.pth’?

### ISSUE THREAD

**Issue by Achestnut00** [WindVChen/DiffAttack#22]
When I try to use the Stanford_Car dataset, I need to provide the weights file ‘STCAR_Res_94.35.pth’, but I didn't find a link to download it in github.

**Comment by WindVChen** [comment]
Hi @Achestnut00,

You can access it as mentioned here:
![image](https://github.com/user-attachments/assets/04698c8d-9476-4d74-8983-e5e0c786b399)

Specifically, in [BIA](https://github.com/Alibaba-AAIG/Beyond-ImageNet-Attack?tab=readme-ov-file), you can find the download link below:
![image](https://github.com/user-attachments/assets/89f834da-5a85-480a-948e-74ac65a2ac7a)

**Comment by Achestnut00** [comment]
Special thanks, I've found it. Have a nice life.
