### ISSUE TITLE
request for the FSGM code or parameters in the comparation table

### ISSUE THREAD

**Issue by ahaha0000** [WindVChen/DiffAttack#3]
Thanks for your excellent work. 😃 

We wonder the concrete FSGM parameters used in your paper, since we did not find any code for them in this repo. 
Conventionally, the FSGM parameters are attack steps `steps`, total threshold `eps` and the step size `alpha`.
Otherwise, the numerical results should be somewhat explained in the `README.md` to allow verification.

Thanks again for your response.

**Comment by WindVChen** [comment]
Hi @ahaha0000 ,

Thanks for your attention. For those I-FGSM-based methods, the number of `steps` is set to 10, the threshold `eps` is set to 16, and the step size `alpha` is set to `eps/steps`. These parameters are actually aligned with the recent transferable attack methods. 

For quick verification, you can directly run the source code of the compared methods without many changes (only change the resolution to 224): [PI-FGSM](https://github.com/qilong-zhang/Patch-wise-iterative-attack/tree/master/Pytorch%20version), [S<sup>2</sup>I-FGSM](https://github.com/yuyang-long/SSA/tree/master). [NCF](https://github.com/VL-Group/Natural-Color-Fool), [PerC-AL](https://github.com/ZhengyuZhao/PerC-Adversarial). For MI-FGSM, DI-FGSM, and TI-FGSM, we make use of the implementations in [S<sup>2</sup>I-FGSM](https://github.com/yuyang-long/SSA/tree/master).

**Comment by Kahsolt** [comment]
Thanks for your quick response and provided appendant materials 😃
