### ISSUE TITLE
关于复现论文结果不正确

### ISSUE THREAD

**Issue by yhl2018** [WindVChen/DiffAttack#34]
感谢你[DiffAttack](https://github.com/WindVChen/DiffAttack)的工作，我在复现的过程中遇到了下面的问题，想请教您一下：
以下实验都是使用的代码仓库中默认设置
1、首先运行了Crafting Adversarial Examples logs是这样的

![image](https://github.com/user-attachments/assets/438661c0-a026-4cea-b08d-7a8b0ceafed4)

2、但是我在执行Evaluation的时候--images_root设置的第一步的output，原型的结果是不对的：
![image](https://github.com/user-attachments/assets/14921d8b-630d-44f1-af5d-82478392d0f1)

跑了两次都是类似的结果，不知道是哪里设置有问题。所以想请教一下

**Comment by yhl2018** [comment]
如果只是测试demo中的数据反而是有效的，
![1733536639646](https://github.com/user-attachments/assets/9f6ff413-42d0-4cc7-a2f0-8f7086893c09)
是否是因为，图像文件命名的问题呢？
![1733536679204](https://github.com/user-attachments/assets/8a3467cc-e0be-4f1d-9eea-ff6ba4cdacca)

**Comment by WindVChen** [comment]
哈喽 @yhl2018 ，

从所贴的结果看，不管是干净样本还是对抗样本的分类准确率都为0，可以检查一下图像和标签是否按顺序一一正确配对，可能是因为所测试的数据集图像和标签没有正确匹配（比如标签起始Index不一致，或者图像命名乱序等）导致准确率都为0.

希望有所帮助~

**Comment by yhl2018** [comment]
我是直接将分享的数据集解压运行的，出现了上述问题。简单的复制了300张单独测试也是好的。
https://drive.google.com/file/d/1sAD1aVLUsgao1X-mu6PwcBL8s68dm5U9/view

**Comment by WindVChen** [comment]
是指随机从数据集抽取300张运行没问题，但整个数据集跑就会出现上面的问题吗？

**Comment by yhl2018** [comment]
我是取得前300张，测试的是没问题，至少准确率不会是0。所以就很奇怪

**Comment by WindVChen** [comment]
Emmm 确实蛮奇怪的，可以看下图像数组和标签数组顺序上是否一一对应，比如用了全部数据后，会不会导致数组顺序有所变动，导致标签和图像都对不上

**Comment by WindVChen** [comment]
方便的话可以将1000张的测试结果发我一下，我这边看看是啥问题~

**Comment by yhl2018** [comment]
我重新复制粘贴出来，结果突然 就对了，可能哪些细节出现了问题
