### ISSUE TITLE
论文实验结果中ddim反转次数是5，代码中反转次数是20？

### ISSUE THREAD

**Issue by Mogul-Ax** [WindVChen/DiffAttack#36]
请问是我对代码理解的不对吗？

**Comment by WindVChen** [comment]
哈喽 @Mogul-Ax ，

代码里也是反转5次哈，可以参看这一块的代码（DDIM设置为20步，然后是从第15步开始）：

https://github.com/WindVChen/DiffAttack/blob/b90edffe932d19ee77d1aa849bc86a96d17c2c52/main.py#L30C1-L31C102

**Comment by Mogul-Ax** [comment]
大佬，很抱歉再次打扰到您，我还是不理解为什么ddim inversion只进行了5次，我看代码中def ddim_reverse_sample(image, prompt, model, num_inference_steps: int = 20, guidance_scale: float = 2.5,res=512):这一函数设置的步数为20，难道原始图像x0反转到xt不是进行了20次吗，为什么说只反转了5次。

**Comment by WindVChen** [comment]
哈喽，论文中的反转5次，是指在总步长为20的设置下，只利用最后5步

代码中`ddim_reverse_sample()`函数反转了20步，但只从倒数第5步开始做优化，并没有利用前面15步的结果，可参考这里：
https://github.com/WindVChen/DiffAttack/blob/b90edffe932d19ee77d1aa849bc86a96d17c2c52/diff_latent_attack.py#L388C1-L395C47

**Comment by Mogul-Ax** [comment]
感谢大佬回复，还有最后一个问题想咨询下大佬，https://github.com/WindVChen/DiffAttack/blob/b90edffe932d19ee77d1aa849bc86a96d17c2c52/diff_latent_attack.py#L388C1-L395C47
这段代码执行过   
inversion_latents = inversion_latents[::-1]以及latent = inversion_latents[start_step - 1]之后
latent是否是x_15？如果不是麻烦大佬指正一下，万分感谢！！

**Comment by WindVChen** [comment]
如果按x_0为干净图像，x_T为噪声图像来看的话，latent应该为x_5位置左右

**Comment by Mogul-Ax** [comment]
感谢大佬解惑，祝大佬科研顺利！
